name: Pull requests
on:
  pull_request:
jobs:
  test:
    name: Test on ${{ matrix.os }} (Node v${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node: ["14.x", "16.x", "18.x"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i
      - run: npm t
